### ISSUE TITLE
Issues with Next.js 14 (typescript, eslint)

### ISSUE THREAD

**Issue by fschlegelone** [catppuccin/tailwindcss#18]
As you can see in the screenshot, I get an error when adding prefix & defaultFlavour to the tailwind config: 
Type error: This expression is not callable.
  Type 'typeof import("/opt/repos/projects/portfolio/node_modules/.pnpm/@catppuccin+tailwindcss@0.1.6_tailwindcss@3.4.1/node_modules/@catppuccin/tailwindcss/dist/index")' has no call signatures.

![CleanShot 2024-02-18 at 16 28 02@2x](https://github.com/catppuccin/tailwindcss/assets/118682177/70b2b901-0965-4ff3-8dbc-4a96f56abbb7)

When removing the prefix & defaultFlavour, it works.. 
![CleanShot 2024-02-18 at 16 30 14@2x](https://github.com/catppuccin/tailwindcss/assets/118682177/a143b228-14a1-4baf-bd68-6e65d05dca49)

**Comment by joulev** [comment]
This is not related to Next.js. You can simply make a `foo.js` file with this content

```js
// @ts-check
const foo = require("@catppuccin/tailwindcss");

foo({}); // TS error
foo.default({}); // TS is happy
```

to reproduce the error.

**From a quick glance, the cause is that `@catppuccin/tailwindcss` should've used `export =` instead of `export default`.**

What you can do right now while waiting for this bug to be patched: use `tailwind.config.ts` instead where you can use ESM syntax

```ts
// tailwind.config.ts
import type { Config } from "tailwindcss";
import tailwindForms from "@tailwindcss/forms";
import catppuccin from "@catppuccin/tailwindcss";

const config: Config = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,tsx}', '.css/**/*.css'],
  theme: {},
  safelist: [
    // this is for demonstration purposes only, not required for basic usage
    {
      pattern: /bg-.+/,
    },
  ],
  plugins: [
    tailwindForms,
    catppuccin({
      prefix: 'one',
      defaultFlavour: 'mocha',
    }),
  ],
};

export default config;
```
