### ISSUE TITLE
Using other flavours inside an element that already contains a flavour seems to break the default flavour.

### ISSUE THREAD

**Issue by sph3** [catppuccin/tailwindcss#3]
Title may have been confusing, so I'll show an example.

Suppose you have the defaultFlavour set to 'latte' and the class 'ctp-latte' on your body element.
Now picture this theme picker:

![image](https://user-images.githubusercontent.com/59633047/178884410-56f9a7f9-b66d-46af-ac17-5b11b897d41c.png)

It seems fine when the selected flavour is the default one. But when I change it to another one, Mocha for example:
![image](https://user-images.githubusercontent.com/59633047/178884702-22bc1c5d-1b92-4f06-8e85-6207bad86f9b.png)

It adopts the colors from the current flavour instead of keeping its own colors, even when its class is set to 'ctp-latte'.
The code for each flavour demo is basically this:
```
<div className='ctp-{flavor}'>
  // flavour name and demo colors
</div>
```
And I'm setting the global theme on the wrapping `div` on App.tsx (I'm using React).
Hope you understand my explanation :)

**Comment by nekowinston** [comment]
Oh, apologies for not commenting on this earlier, I will check it out this weekend.

**Comment by nekowinston** [comment]
I believe I have identified a possible issue, could you please give the following settings a shot?
Try setting the `defaultFlavour` to `""`
```js
  plugins: [require("@catppuccin/tailwindcss")({
      defaultFlavour: "",
  })],
```
This will make the `:root` unset, which can cause some hierarchy issues with how classes are being applied.

Please let me know if this helps at all, I will investigate further.

**Comment by sph3** [comment]
Yes, leaving the `defaultFlavour` blank worked!
![image](https://user-images.githubusercontent.com/59633047/180269739-145c02aa-f191-411b-8e96-901b515e46b8.png)

**Comment by nekowinston** [comment]
Great! 🎉 
**Not setting** the `defaultFlavour` should probably be the default setting, so that:
```js
  plugins: [require("@catppuccin/tailwindcss")],
```

Doesn't manipulate the `:root`.

I will adjust the defaults for the plugin, and notify users about a somewhat breaking change in that regard.
Thanks a lot for helping me figure this out! 👍 

(I will also include an update regarding #2, making Mocha the default previews until a better solution is found.)

**Comment by sph3** [comment]
That's awesome! Thank you for your time 😊
